### ISSUE TITLE
Rotating a polygon with hole

### ISSUE THREAD

**Issue by G4mingEdition** [Falke-Design/leaflet.pm#14]
Hi,

I'm using the "rotationV2" branch and I encountered a bug.
If you try to rotate a polygon with a hole, hole's points aren't rotating.
![image](https://user-images.githubusercontent.com/38436883/116058563-40e97b00-a680-11eb-8d36-ebe665880394.png)

To fix the problem, I have edited "../js/Mixins/Rotating.js".
**Then**
![image](https://user-images.githubusercontent.com/38436883/116058672-5b235900-a680-11eb-9777-6603aacee269.png)
**Now**
![image](https://user-images.githubusercontent.com/38436883/116058717-66768480-a680-11eb-9c13-8b0efa57226c.png)

**Comment by Falke-Design** [comment]
Can you please try to use the develop branch from Leaflet-Geoman, we already merged this PR.
If the problem still exists, please create a issue in the Leaflet-Geoman Repo.

But thanks for reporting, I will take a look into it.

**Comment by Falke-Design** [comment]
More better would be if you create a PR which fixes this bug. It looks like you already know what is needed to be fix it ;)

**Comment by G4mingEdition** [comment]
Ok ;)
